server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://db:5432/mydb
    username: myuser
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update # 컬럼 자동 생성 및 업데이트 활성화
    show-sql: true # 이 부분 추가

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"

secret:
  key: mySecretKey
